# Site settings
title: Lirong Hu
email: hlrarong@163.com
description: > # this means to ignore newlines until "baseurl:"
  This is where Lirong Hu documents thoughts and ideas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hlrarong.github.io" # the base hostname & protocol for your site
github_username:  hlrarong

# Build settings
markdown: kramdown